config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: { registrations: 'registrations' }
  
  root 'main#index'
  get '/profile', to: 'users#profile'
  get '/file/:id', to: 'documents#show'
  get '/admin/files/list', to: 'admin/documents#list'

  resources :users, only: [:show]
  
  namespace :admin do
    root 'main#index'
    resources :documents, path: 'files'
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :pages
    resources :blocks
    resources :settings, only: [:index, :update]
    resources :styles, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :products
    resources :product_categories
    resources :xmls

    get 'services/sync', to: 'services#sync_page'
    post 'services/sync', to: 'services#sync'
    post 'services/join/:id', to: 'xmls#join'
  end

  get '/xml/:slug', to: 'xmls#show'
  get '/products/:slug', to: 'products#show'
  get '/categories/:slug', to: 'products#show_category_items'
  get '/sitemap', to: 'main#sitemap'
  get '/:slug', to: 'main#show'

end

app/models/page.rb
class Page < ApplicationRecord
  include ActionView::Helpers::TagHelper

  belongs_to :category, foreign_key: 'page_category_id', optional: true
  has_and_belongs_to_many :styles
  validates :title, presence: true

  def style_content
    content = []
    self.styles.each { |style| content.push(style.content) }

    content_tag(:style, content.join(' ').html_safe) if content.any?
  end

end

app/views/admin/pages/_form.html.slim
javascript:
  var page = #{@page.content.nil? ? "{blocks:[]}".html_safe : prepare_content(@page.content)}
  var loc = #{rte_localization}
  var block_templates = #{Block.json_list.html_safe}
  var language = "#{I18n.locale}"

= @page.style_content

div class="content rte rte_editor"

= form_with model: [:admin, @page], class: 'rte_result_form' do |f|
  div class="mb-2"
    = f.label :title, t('.title'), class: "mb-1"
    = f.text_field :title, class: "result_title form-control", required: true
  div class="mb-2"
    = f.label :slug, t('.slug'), class: "mb-1"
    = f.text_field :slug, class: "result_path form-control"
  div class="mb-2"
    = f.label :style_ids, t('.css'), class: "mb-1"
    = f.select :style_ids, options_from_collection_for_select(Style.all, :id, :title), {include_blank: true}, {class: "result_styles form-select mb-2", multiple: true}
  div class="mb-2"
    = f.label :page_category_id, t('.category'), class: "mb-1"
    = f.collection_select :page_category_id, PageCategory.order(:title), :id, :title, {include_blank: true}, {class: "form-select mb-2"}
  hr class="mb-2"
  div class="mb-2"
    = f.label :description, t('.desc')
    = f.text_area :description, class: "form-control"
  div class="mb-2"
    = f.label :og_title, t('.og_title'), class: "mb-1"
    = f.text_field :og_title, class: "form-control"
  div class="mb-2"
    = f.label :og_type, t('.og_type'), class: "mb-1"
    = f.text_field :og_type, class: "form-control"
  div class="mb-2"
    = f.label :og_image, t('.og_image'), class: "mb-1"
    = f.text_field :og_image, class: "form-control", data: { target: 'ogimage'}
    = content_tag :div, 'Select', class: 'btn btn-sm btn-primary mt-2 w-100', data: { action: 'fs', target: 'ogimage'}
  div class="mb-2"
    = f.label :og_url, t('.og_url'), class: "mb-1"
    = f.text_field :og_url, class: "form-control"
  div class="mb-2"
    = f.label :og_description, t('.og_desc'), class: "mb-1"
    = f.text_area :og_description, class: "form-control"
  div class="form-check mb-1"
    = f.check_box :index, class: 'form-check-input'
    = f.label :index, 'index page', class: 'form-check-label'
  div class="form-check"
    = f.check_box :follow, class: 'form-check-input'
    = f.label :follow, 'follow page', class: 'form-check-label'

  = f.text_area :content, class: 'result_content'
  = f.submit 'submit', class: 'rte_submit'

<script src="https://pagecdn.io/lib/ace/1.4.13/ace.min.js" crossorigin="anonymous" integrity="sha256-GjtAsBCI/KPlEYQf0I8yNimcThRoWMnk7Vpi+dUt+GY=" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.14/ext-language_tools.min.js" integrity="sha512-S7Whi8oQAQu/MK6AhBWufIJIyOvqORj+/1YDM9MaHeRalsZjzyYS7Usk4fsh+6J77PUhuk5v/BxaMDXRdWd1KA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
script src="https://cdn.jsdelivr.net/npm/suneditor@latest/dist/suneditor.min.js"
script src="https://cdn.jsdelivr.net/npm/suneditor@latest/src/lang/ko.js"
= javascript_import_module_tag "rte"

app/views/admin/pages/_page.html.slim
= content_tag :tr, data: { category: page.category.nil? ? t('.nocategory') : page.category.title }
  td = page.title
  td.text-muted = page.slug
  td.text-muted = page.category.nil? ? t('.nocategory') : page.category.title
  td.text-muted = page.created_at.strftime("%d.%m.%Y %H:%M:%S")
  td.text-muted = page.updated_at.strftime("%d.%m.%Y %H:%M:%S")
  td
    div class="d-flex justify-content-end"
      = link_to t('.show'), admin_page_path(page), class: 'btn btn-sm btn-dark me-2'
      = link_to t('.edit'), edit_admin_page_path(page), class: 'btn btn-sm btn-dark me-2', data: { turbo: false }
      = link_to t('.delete'), admin_page_path(page), data: {'turbo-method' => :delete}, class: 'btn btn-sm btn-danger'
 

app/views/admin/pages/edit.html.slim
= render 'form'

app/views/admin/pages/index.html.slim
div class="content p-2 pt-3"
  .container-fluid

    div class="d-flex align-items-center"
      h1 style="margin-right: 1rem" #{t('.header')}
      = link_to t('.new'), new_admin_page_path, class: 'btn btn-sm btn-dark', data: { turbo: false }

    hr

    div.table-responsive
      table class="table"
        thead
          tr
            th = t('.title')
            th = t('.slug')
            = content_tag :th, t('.category'), data: {sortby: 'category'}
            th = t('.created')
            th = t('.updated')
        tbody
          == render @pages

= javascript_import_module_tag "sorting"

app/views/admin/pages/new.html.slim
= render 'form'    

app/views/admin/pages/show.html.slim
- content_for :global_styles, @setting.style_content unless @setting.style.nil?
- content_for :page_styles, @page.style_content if @page.styles.any?

.content
  == render 'shared/header'

  = html_content @page
  
  == render 'shared/footer'