config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: { registrations: 'registrations' }
  
  root 'main#index'
  get '/profile', to: 'users#profile'
  get '/file/:id', to: 'documents#show'
  get '/admin/files/list', to: 'admin/documents#list'

  resources :users, only: [:show]
  
  namespace :admin do
    root 'main#index'
    resources :documents, path: 'files'
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :pages
    resources :blocks
    resources :settings, only: [:index, :update]
    resources :styles, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :products
    resources :product_categories
    resources :xmls

    get 'services/sync', to: 'services#sync_page'
    post 'services/sync', to: 'services#sync'
    post 'services/join/:id', to: 'xmls#join'
  end

  get '/xml/:slug', to: 'xmls#show'
  get '/products/:slug', to: 'products#show'
  get '/categories/:slug', to: 'products#show_category_items'
  get '/sitemap', to: 'main#sitemap'
  get '/:slug', to: 'main#show'

end

app/models/block.rb
class Block < ApplicationRecord
  include ActionView::Helpers
  
  validates :title, presence: true

  belongs_to :category, foreign_key: 'block_category_id', optional: true

  def prepare_template
    template = self.content.is_a?(String) ? ActiveSupport::JSON.decode(self.content) : self.content

    template['title'] = self.title
    template['block'] = self.container_tag
    template['rtype'] = self.rte_type
    template['template_name'] = self.template_name
    template['category'] = self.category.nil? ? t('admin.blocks.block.nocategory') : self.category.title
    
    template
  end

  def self.json_list
    result = {blocks: []}

    self.all.each do |block|
      result[:blocks].push(block.prepare_template)
    end
    
    result[:blocks].push({block: 'div', title: 'Advanced block', block_name: 'mg_adv', template_name: 'advanced'})
    result.to_json
  end

end

app/controllers/admin/blocks_controller.rb
class Admin::BlocksController < Admin::MainController

  before_action :set_block, only: [:show, :edit, :update, :destroy]
  
  def index
    @blocks = {
      system_blocks: Block.where(is_system: true).order(id: :asc),
      regular_blocks: Block.where(is_system: false).order(id: :asc)
    }
  end

  def show
  end

  def new
    @block = Block.new
  end

  def create
    @block = Block.new(block_params)

    if @block.save
      redirect_to admin_blocks_path, flash: { success: t('.success') }
    else
      flash[:danger] = t('.fail')
      render :new
    end
  end

  def update
    if @block.update(block_params)
      redirect_to admin_blocks_path, flash: { success: t('.success') }
    else
      flash[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    @block.destroy

    redirect_to admin_blocks_path, flash: { success: t('.success') }
  end

  private

  def set_block
    @block = Block.find(params[:id])
  end

  def block_params
    params.require(:block).permit([:title, :template_name, :content, :block_category_id, :is_system, :container_tag, :rte_type])
  end
    
end

app/views/admin/blocks/_block.html.slim
= content_tag :tr, data: { category: block.category.nil? ? t('.nocategory') : block.category.title }

  td = block.title
  td.text-muted = block.template_name
  td.text-muted = block.category.nil? ? t('.nocategory') : block.category.title
  td
    div class="d-flex justify-content-end"
      = link_to t('.show'), admin_block_path(block), class: 'btn btn-sm btn-dark me-2'
      = link_to t('.edit'), edit_admin_block_path(block), class: 'btn btn-sm btn-dark me-2', data: { turbo: false }
      = link_to t('.delete'), admin_block_path(block), data: {'turbo-method' => :delete}, class: 'btn btn-sm btn-danger'

app/views/admin/blocks/_form.html.slim
javascript:
  var page = #{@block.content.nil? ? "{blocks:[]}".html_safe : prepare_content(@block.content)}
  var loc = #{rte_localization}
  var block_templates = #{Block.json_list.html_safe}
  var language = '#{I18n.locale}'
  
div class="content rte rte_editor"

div style="visibility: collapse"
  = form_with model: [:admin, @block], class: 'rte_result_form' do |f|
    div class="mb-2"
      = f.label :title, t('.title')
      = f.text_field :title, class: "result_title form-control"
    div class="mb-2"
      = f.label :container_tag, t('.container_tag')
      = f.text_field :container_tag, class: "result_title form-control"
    div class="mb-2"
      = f.label :template_name, t('admin.blocks.index.desc')
      = f.text_field :template_name, class: "result_template form-control"
    div class="mb-2"
      = f.label :block_category_id, t('.category'), class: "mb-1"
      = f.collection_select :block_category_id, BlockCategory.order(:title), :id, :title, {include_blank: true}, {class: "form-select mb-2"}
    div class="mb-2"
      = f.label :rte_type, t('.rte_type')
      = f.text_field :rte_type, class: "result_title form-control"
    div class="form-check"
      = f.check_box :is_system, class: 'form-check-input'
      = f.label :is_system, t('admin.blocks.index.system'), class: 'form-check-label'
    = f.text_area :content, class: 'result_content'
    = f.submit 'submit', class: 'rte_submit'  

<script src="https://pagecdn.io/lib/ace/1.4.13/ace.min.js" crossorigin="anonymous" integrity="sha256-GjtAsBCI/KPlEYQf0I8yNimcThRoWMnk7Vpi+dUt+GY=" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.14/ext-language_tools.min.js" integrity="sha512-S7Whi8oQAQu/MK6AhBWufIJIyOvqORj+/1YDM9MaHeRalsZjzyYS7Usk4fsh+6J77PUhuk5v/BxaMDXRdWd1KA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
script src="https://cdn.jsdelivr.net/npm/suneditor@latest/dist/suneditor.min.js"
script src="https://cdn.jsdelivr.net/npm/suneditor@latest/src/lang/ko.js"
= javascript_import_module_tag "rte"

app/views/admin/blocks/edit.html.slim
= render 'form'

app/views/admin/blocks/index.html.slim
div class="content p-2 pt-3"
  .container-fluid

    div class="d-flex align-items-center"
      h1 style="margin-right: 1rem" #{t('.header')}
      = link_to t('.new'), new_admin_block_path, class: 'btn btn-sm btn-dark', data: { turbo: false }

    hr

    div class="table-responsive mb-5"
      table class="table"
        thead
          tr
            th = t('.title')
            th = t('.desc')
            = content_tag :th, t('.category'), data: { sortby: 'category', sortarea: '.sort_area' }
        tbody class="sort_area"
          == render @blocks[:regular_blocks]

    h3 = t('.system')
    div class="table-responsive mb-5"
      table class="table"
        thead
          tr
            th = t('.title')
            th = t('.desc')
            th = t('.category')
        tbody
          == render @blocks[:system_blocks]

= javascript_import_module_tag "sorting"

app/views/admin/blocks/new.html.slim
= render 'form'

app/views/admin/blocks/show.html.slim
- content_for :global_styles, @setting.style_content unless @setting.style.nil?

.content
  = html_content @block