config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: { registrations: 'registrations' }
  
  root 'main#index'
  get '/profile', to: 'users#profile'
  get '/file/:id', to: 'documents#show'
  get '/admin/files/list', to: 'admin/documents#list'

  resources :users, only: [:show]
  
  namespace :admin do
    root 'main#index'
    resources :documents, path: 'files'
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :pages
    resources :blocks
    resources :settings, only: [:index, :update]
    resources :styles, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :products
    resources :product_categories
    resources :xmls

    get 'services/sync', to: 'services#sync_page'
    post 'services/sync', to: 'services#sync'
    post 'services/join/:id', to: 'xmls#join'
  end

  get '/xml/:slug', to: 'xmls#show'
  get '/products/:slug', to: 'products#show'
  get '/categories/:slug', to: 'products#show_category_items'
  get '/sitemap', to: 'main#sitemap'
  get '/:slug', to: 'main#show'

end

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  - if key == 'alert'
    div class="alert flash alert-danger" role="alert" #{message}
  - elsif key == 'notice'
    div class="alert flash alert-primary" role="alert" #{message}
  - else
    div class="alert flash alert-#{key}" role="alert" #{message}

app/views/shared/_footer.html.slim
= html_content @setting.footer if @setting && @setting.footer

app/views/shared/_header.html.slim
= html_content @setting.header if @setting && @setting.header

/ - if user_signed_in?
/   = button_to t('logout'), destroy_user_session_path, method: :delete, class: 'btn btn-link'
/ - else
/   = link_to t('signup'), new_user_registration_path
/   = link_to t('login'), new_user_session_path

app/views/shared/_sidebar.html.slim
div class="sidebar_front d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="height: 100vh; position: fixed"
  
  a href="#{ root_path }" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none"
    - if @setting.logo.attached?
      = image_tag(@setting.logo, style: 'height: 32px', class: 'me-2')
    - else
      span class="fs-4" = @setting.site_name
  
  hr

  ul class="nav nav-pills flex-column mb-auto"
    = sidebar_item t('home'), admin_root_path, 'house'
    = sidebar_item t('admin.pages.index.header'), admin_pages_path, 'window'
    = sidebar_item t('admin.blocks.index.header'), admin_blocks_path, 'braces'
    = sidebar_item t('admin.documents.index.header'), admin_documents_path, 'file-earmark'
    = sidebar_item t('admin.categories.index.header'), admin_categories_path, 'tags'
    
    - if @setting.active_store
      hr
        = sidebar_item t('admin.products.index.header'), admin_products_path, 'shop'
        = sidebar_item t('admin.categories.index.header'), admin_product_categories_path, 'tags'
        - if @setting.active_store_sync
          = sidebar_item t('store_sync'), admin_services_sync_path, 'arrow-repeat'
    - if @setting.xml_joiner
      hr
        = sidebar_item t('admin.xmls.index.header'), admin_xmls_path, 'filetype-xml'
        = sidebar_item t('admin.xmls.new.header'), new_admin_xml_path, 'plus-square'
    hr
    = sidebar_item t('admin.users.index.header'), admin_users_path, 'people'
    = sidebar_item t('admin.styles.index.header'), admin_styles_path, 'filetype-css'
    = sidebar_item t('admin.settings.index.header'), admin_settings_path, 'gear-wide'
    
  hr

  div class="dropdown"
    a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser" data-bs-toggle="dropdown" aria-expanded="false"
      img src="#{current_user.avatar_url([32,32])}" alt="avatar" class="rounded-circle me-2" width="32" height="32"
      strong #{current_user.first_name} #{current_user.last_name}
    ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser"
      li
        = link_to t('profile'), profile_path, class: 'dropdown-item'
      li
        hr class="dropdown-divider"
      li
        = button_to t('logout'), destroy_user_session_path, method: :delete, class: 'dropdown-item'

div class="sidebar_back d-flex flex-column flex-shrink-0 p-3 text-white bg-dark"