config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: { registrations: 'registrations' }
  
  root 'main#index'
  get '/profile', to: 'users#profile'
  get '/file/:id', to: 'documents#show'
  get '/admin/files/list', to: 'admin/documents#list'

  resources :users, only: [:show]
  
  namespace :admin do
    root 'main#index'
    resources :documents, path: 'files'
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :pages
    resources :blocks
    resources :settings, only: [:index, :update]
    resources :styles, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :products
    resources :product_categories
    resources :xmls

    get 'services/sync', to: 'services#sync_page'
    post 'services/sync', to: 'services#sync'
    post 'services/join/:id', to: 'xmls#join'
  end

  get '/xml/:slug', to: 'xmls#show'
  get '/products/:slug', to: 'products#show'
  get '/categories/:slug', to: 'products#show_category_items'
  get '/sitemap', to: 'main#sitemap'
  get '/:slug', to: 'main#show'

end

app/models/product.rb
class Product < ApplicationRecord
  # belongs_to :template, class_name: 'Block', foreign_key: 'template_id', optional: true, dependent: :destroy
  belongs_to :category, foreign_key: 'product_category_id', optional: true
  belongs_to :template, class_name: 'Block', optional: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::MainController
  
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    
    if @product.save
      redirect_to admin_products_path, flash: { success: t('.success') }
    else
      flash[:danger] = t('.fail')
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to admin_products_path, flash: { success: t('.success') }
    else
      flash[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    @product.destroy

    redirect_to admin_products_path, flash: { success: t('.success') }
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    result = params.require(:product).permit([:title, :slug, :product_category_id, :template_id,
                                      :description, :available, :price, :currency, :picture_url, :content,
                                      :og_title, :og_type, :og_image, :og_url, :og_description])
    result[:content] = ActiveSupport::JSON.decode(result[:content]) if !result[:content].nil? && result[:content].is_a?(String)
    result
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.all
  end

  def show
    @product = Product.find_by(slug: params[:slug])
  end

  def show_category_items
    @category = ProductCategory.find_by(slug: params[:slug])
    @products = @category.items
  end

end

app/views/admin/products/_form.html.slim
= form_with model: [:admin, @product] do |f|
  .mb-2
    = f.label :title, t('.title'), class: "mb-1"
    = f.text_field :title, class: "result_title form-control", required: true
  .mb-2
    = f.label :slug, t('.slug'), class: "mb-1"
    = f.text_field :slug, class: "result_path form-control"
  .mb-2
    = f.label :product_category_id, t('.category'), class: "mb-1"
    = f.collection_select :product_category_id, ProductCategory.order(:title), :id, :title, {include_blank: true}, {class: "form-select mb-2"}
  
  hr.mb-2

  .mb-2
    = f.label :description, t('.description'), class: "mb-1"
    = f.text_area :description, class: "form-control"

  .mb-2
    = f.label :price, t('.price'), class: "mb-1"
    = f.number_field :price, class: "form-control"

  .mb-2
    = f.label :currency, t('.currency'), class: "mb-1"
    = f.text_field :currency, class: "form-control"

  div class="form-check mb-3"
    = f.check_box :available, class: 'form-check-input'
    = f.label :available, t('.available'), class: 'form-check-label'
  
  hr.mb-2

  .mb-2
        = f.label :template_id, t('.template'), class: 'form-label'
        = f.collection_select :template_id,
                              Block.where(is_system: true).order(:title), :id, :title,
                              {include_blank: true}, {class: "form-select"}

  hr class="mb-2"
  
  div class="mb-2"
    = f.label :og_title, t('.og_title'), class: "mb-1"
    = f.text_field :og_title, class: "form-control"
  div class="mb-2"
    = f.label :og_type, t('.og_type'), class: "mb-1"
    = f.text_field :og_type, class: "form-control"
  div class="mb-2"
    = f.label :og_image, t('.og_image'), class: "mb-1"
    = f.text_field :og_image, class: "form-control", data: { target: 'ogimage'}
  div class="mb-2"
    = f.label :og_url, t('.og_url'), class: "mb-1"
    = f.text_field :og_url, class: "form-control"
  div class="mb-2"
    = f.label :og_description, t('.og_desc'), class: "mb-1"
    = f.text_area :og_description, class: "form-control"
  
  .mb-3
        = f.submit t('.save'), class: 'btn btn-sm btn-primary'

app/views/admin/products/_product.html.slim
= content_tag :tr, data: { category: product.category.nil? ? t('.nocategory') : product.category.title }
  td = product.title
  td.text-muted = product.slug
  td.text-muted = product.category.nil? ? t('.nocategory') : product.category.title
  td.text-muted = product.created_at.strftime("%d.%m.%Y %H:%M:%S")
  td.text-muted = product.updated_at.strftime("%d.%m.%Y %H:%M:%S")
  td
    div class="d-flex justify-content-end"
      = link_to t('.show'), admin_product_path(product), class: 'btn btn-sm btn-dark me-2'
      = link_to t('.edit'), edit_admin_product_path(product), class: 'btn btn-sm btn-dark me-2', data: { turbo: false }
      = link_to t('.delete'), admin_product_path(product), data: {'turbo-method' => :delete}, class: 'btn btn-sm btn-danger'
 

app/views/admin/products/edit.html.slim
div class="content p-2 pt-3"
  .container-fluid

    div class="d-flex align-items-center"
      h1 style="margin-right: 1rem" #{t('.header')}

    hr

    = render 'form'

app/views/admin/products/index.html.slim
div class="content p-2 pt-3"
  .container-fluid

    div class="d-flex align-items-center"
      h1 style="margin-right: 1rem" #{t('.header')}
      = link_to t('.new'), new_admin_product_path, class: 'btn btn-sm btn-dark', data: { turbo: false }

    hr

    div.table-responsive
      table class="table"
        thead
          tr
            th = t('.title')
            th = t('.slug')
            = content_tag :th, t('.category'), data: {sortby: 'category'}
            th = t('.created')
            th = t('.updated')
        tbody
          == render @products

= javascript_import_module_tag "sorting"

app/views/admin/products/new.html.slim
div class="content p-2 pt-3"
  .container-fluid

    div class="d-flex align-items-center"
      h1 style="margin-right: 1rem" #{t('.header')}

    hr

    = render 'form'

app/views/admin/products/show.html.slim
- content_for :global_styles, @setting.style_content unless @setting.style.nil?

.content
  = html_content @product, @product.template.nil? ? @setting.product_template.content : @product.template.content